# Monitors (See https://wiki.hyprland.org/Configuring/Monitors/)
monitor=,highres,auto,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = hyprpaper
#exec-once = waybar
exec-once = eww daemon && eww open bar

# DOTFILES TO RUN
exec-once = "$HOME/dotfiles/hypr/backgroundChange.sh"
