########################################
# AutoStart Configuration for Hyprland #
# Author: Al4st0r                      #
########################################

# Monitors (See https://wiki.hyprland.org/Configuring/Monitors/)
monitor=,highres,auto,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
#exec-once = waybar
exec-once = eww daemon && eww open bar
#exec-once = hyprpaper && sleep 2 && "$HOME/dotfiles/hypr/backgroundChange.sh"
exec-once = $HOME/dotfiles/hypr/backgroundChange.sh
exec-once = dunst
