# Monitors (See https://wiki.hyprland.org/Configuring/Monitors/)
monitor=,highres,auto,1

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = hyprpaper
exec-once = waybar
exec-once = SUPER, M, exec, [workspace special:magic; float; move 1490 50; size 400 580] youtube-music
exec-once = SUPER, M, exec, [workspace special:magic; float; move 1490 640; size 400 410] kitty pacmixer
exec-once = [workspace 1] obsidian