#!/bin/bash

current_brightness=$(brightnessctl get)
max_brightness=$(brightnessctl max)

brightness=$(awk -v current_brightness=$current_brightness -v max_brightness=$max_brightness 'BEGIN {print int(current_brightness/max_brightness*100)}')

if [[ $brightness -ge 50 ]]; then
    icon=""
else
    icon=""
fi

if [[ "$1" == "--BRIGHT" ]]; then
    echo "$brightness"
elif [[ "$1" == "--ICON" ]]; then
    echo $icon
elif [[ "$1" == "--TOGGLE" ]]; then
    if [[ $brightness -ge 50 ]]; then
        brightnessctl set 1
    else
        brightnessctl set 100%
    fi
fi
