#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli device wifi show | grep SSID | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')

if [ $status ] ; then
    icon=""
    text="Disconnected"
    col="#575268"

else
    icon=""
    text="$essid"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
