# #########################################################
# #########################################################
#
#   oooooooooooooooooooooooooooooooooooooooooooooooooooo
#        _      _    ___           _      ___
#       / \    | |  /   |    ___  | |_   / _ \   _ __
#      / _ \   | | / /| |_  / __| | __| | | | | | '__|
#     / ___ \  | | |__   _| \__ \ | |_  | |_| | | |
#    /_/   \_\ |_|    |_|   |___/  \__|  \___/  |_|
#
#   oooooooooooooooooooooooooooooooooooooooooooooooooooo
#
# #########################################################
# #########################################################

# This configuration has been split into components to make it easier to mantain

# Source files
source = ~/.config/hypr/source/autostart.conf
source = ~/.config/hypr/source/bind.conf
source = ~/.config/hypr/source/environment.conf
source = ~/.config/hypr/source/view.conf
